# HHKB Low-Profile – Shield Configuration

CONFIG_ZMK_KEYBOARD_NAME="kb thats it"

# Bluetooth
CONFIG_ZMK_BLE=y
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5

# USB
CONFIG_ZMK_USB=y

# NFC pins used as GPIO (C11 = P0.10, C12 = P0.09)
CONFIG_NFCT_PINS_AS_GPIOS=y

# Power management
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
